plugins { id 'com.android.application' }
dependencies { testImplementation 'junit:junit:4.13.2' }

android {
    namespace 'ru.skandata.tsd'
    compileSdk 36
    defaultConfig {
        applicationId 'ru.skandata.tsd'
        minSdk 26
        targetSdk 34
        versionCode 3
        versionName '0.1.2'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
